config/routes.rb
EcSite::Application.routes.draw do

  controller :purchase do
    match "purchase/index" => 'purchase#index', :as => 'purchase_start', :via => 'get'
  end

  controller :cart do
    match 'cart/add' => 'cart#add', :as => 'add_cart', :via => 'put'
    match 'cart/delete' => 'cart#delete', :as => 'delete_cart', :via => 'put'
    match 'cart/show' => 'cart#show', :as => 'show_cart', :via => 'get'
  end
  
  namespace :admin do
    resources :items
  end

  resources :items, :only =>[:index, :show]

  root :to => "welcome#index"
  devise_for :users
  
  


end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  #layout 'admin'
  # GET /admin/items
  # GET /admin/items.json
  def index
    #@admin_items = Admin::Item.all
    @items = Item.all
  end

  # GET /admin/items/1
  # GET /admin/items/1.json
  def show

  end

  # GET /admin/items/new
  def new
    #@admin_item = Admin::Item.new
    @item = Item.new
  end

  # GET /admin/items/1/edit
  def edit
  end

  # POST /admin/items
  # POST /admin/items.json
  def create
    #@admin_item = Admin::Item.new(admin_item_params)
    @item = Item.new(item_params)

=begin
respond_to do |format|
if @admin_item.save
format.html { redirect_to @admin_item, notice: 'Item was successfully created.' }
format.json { render action: 'show', status: :created, location: @admin_item }
else
format.html { render action: 'new' }
format.json { render json: @admin_item.errors, status: :unprocessable_entity }
end
end
=end

    respond_to do |format|
      if @item.save
        format.html { redirect_to [:admin, @item], notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: [:admin,@item] }
      else
        format.html { render action: 'new' }
        format.json { render json: [:admin, @item].errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /admin/items/1
  # PATCH/PUT /admin/items/1.json
  def update
=begin
respond_to do |format|
if @admin_item.update(admin_item_params)
format.html { redirect_to @admin_item, notice: 'Item was successfully updated.' }
format.json { head :no_content }
else
format.html { render action: 'edit' }
format.json { render json: @admin_item.errors, status: :unprocessable_entity }
end
end
=end
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to [:admin,@item], notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [:admin,@item].errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /admin/items/1
  # DELETE /admin/items/1.json
  def destroy
=begin
@admin_item.destroy
respond_to do |format|
format.html { redirect_to admin_items_url }
format.json { head :no_content }
end
=end
    @item.destroy
    respond_to do |format|
      format.html { redirect_to admin_items_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    #@admin_item = Admin::Item.find(params[:id])
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    #params.require(:admin_item).permit(:name, :price)
    params.require(:item).permit(:name, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  include Jpmobile::ViewSelector
  trans_sid :always
  hankaku_filter :input => true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    if params[:item_id]
      session[:cart] ||= []
      session[:cart]<<params[:item_id]
    end
    redirect_to :action => 'show'
  end

  def delete
    if params[:item_id] and session[:cart].respond_to?(:delete)
      session[:cart].delete(params[:item_id])
    end
    redirect_to :action => 'show'
  end

  def show
    if session[:cart]
      @items = Item.find(session[:cart])
    else
      @items = []
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  before_filter :authenticate_user! #ログインしてないユーザーがアクセスしてきたときにログイン画面を表示
  
  def index
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/items/_form.html.erb
<%= form_for [:admin, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this admin_item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<h1>Editing admin_item</h1>

<%= render 'form' %>

<%= link_to 'Show',[:admin, @item] %> |
<%= link_to 'Back', admin_items_path %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>商品名</th>
      <th>価格</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', [:admin, item] %></td>
        <td><%= link_to 'Edit', edit_admin_item_path(item) %></td>
        <td><%= link_to 'Destroy', [:admin, item], method: :delete, data: {confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %> 
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_admin_item_path %>

app/views/admin/items/new.html.erb
<h1>新規商品登録</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_items_path %>

app/views/admin/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_admin_item_path(@item) %> |
<%= link_to 'Back', admin_items_path %>

app/views/cart/show.html.erb
<% if notice %>
   <%= notice %>
<% end %>

<h1>カート</h1>

<table class="table">
	<tr class="title">
		<th class="name">商品名</th>
		<th class="price">価格</th>
	</tr>
	<% @items.each do |item| %>
		<tr class="<%= cycle('odd', 'even')%>" >
			<td class="name"><%= item.name %></td>
			<td class="price"><%= item.price %></td>
		</tr>	
	<% end %>
	<tr class="title">
		<th class="name">合計金額</th>
		<th class="price"><%= @items.inject(0){|sum,item| sum + item.price} %></th>
	</tr>
	<tr>
		<td colspan="2" class="name" style="text-align: center;">
			<%= link_to '購入する', purchase_start_url %>
		</td>
	</tr>
</table>

app/views/cart/show_mobile.html.erb
<% if notice %> 
<font color="bule"><%= notice %></font>
<% end %>

<table width="100%">
	<tr>
		<td>商品名</td>
		<td><%= @item.name %></td>
	</tr>
	<tr>
		<td>価格<td>
		<td><%= @item.price %><td>
	</tr>
	<tr>
		<td colspan="2" align="center">
			<%= form_tag(add_cart_url, :method => 'put') do %>%
			    <%= hidden_field_tag :item_id, @item.id %>
			    <%= submit_tag "カートへ追加する" %>
			<% end %>
		</td>
	</tr>
	<tr>
		<td colspan="2" align="center">
			<%= form_tag(purchase_start_url, :method => 'get')do %>
			<%= submit_tag '購入する' %>
			<% end %>
		</td>
	</tr>
</table>

<%= link_to '一覧へ',items_path %>
<br />

app/views/cart/show_smart_phone.html.erb
<ul data-role="listview">
	<li data-theme="C" class="ui-btn ui-btn-icon-right ui-li ui-btn-up-c">
		<div class="ui-btn-inner ui-li">
			<div class="ui-btn-text">
				<a href="index.html" class="ui-link-inherit">
				    <p class="ui-li-aside ui-li-desc">
					&yen; <strong><%= @item.price %></strong>
				    </p> 
				</a>
			</div>
			<%= form_tag(add_cart_url, :method => 'put') do %>
			<%= hidden_field_tag :item_id, @item.id %>
			<button type="submit" data-theme="a" class="ui-btn-hidden" ariadisabled="false">
				カートへ追加する
			</button>
			<% end %>			
		</div>
		<%= form_tag(purchase_start_url, :method => 'get') do %>
		    <%= submit_tag '購入する', :class => "ul-btn-hidden",
		                              "aria-disabled" => "false",
		                              "data-theme" => "a"%>
		<% end %>
	</li>
</ul>

app/views/items/index.html.erb
<h1>商品一覧</h1>

<table class="table">
    <tr class="title">
      <th class="name">商品名</th>
      <th class="price">価格</th>
      <th class="detail"></th>
    </tr>

  <tbody>
    <% @items.each do |item| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to '詳細', item %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/show.html.erb
<table width="100%">

<tr>
  <td>商品名</td>
  <td><%= @item.name %></td>
</tr>

<tr>
  <td>価格:</td>
  <td><%= @item.price %></td>
</tr>
<tr>
	<td colspan="2" align="center">
		<%= form_tag(add_cart_url, :method => 'put') do %>
		  <%= hidden_field_tag :item_id, @item.id %>
		  <%= submit_tag "カートへ追加する" %>
		<% end %>
	</td>
</tr>
</table>

<%= link_to '一覧へ', items_path %>
<br/>

app/views/layouts/_footer.html.erb
&copy; EcSite, inc. <%= Time.now.year %>

app/views/layouts/_footer_mobile.html.erb
<div align="left">
<font size="2">
	&#xE6E2;<%= link_to "トップページ",{:controller => "/welcome", :action =>"index"},
	{:accesskey => "1"} %><br/>
    &#xE6E3;<%= link_to "商品一覧",{:controller => "/items", :action =>"index"},
	{:accesskey => "2"} %><br/>
    &#xE6E4;<%= link_to "送料・お支払について","#",
	{:accesskey => "3"} %><br/>
    &#xE6E5;<%= link_to "お問い合わせ","#",
	{:accesskey => "4"} %><br/>
	<% if current_user %>
	    &#xE6E6;<%= link_to "マイページ", "#",
	    {:accesskey => "5"}%><br/>
	    &#xE6E7;<%= link_to "ログアウト", [:destroy, :user_session],
	    {:accesskey => "6"}%><br/>
	<% else %>
	    &#xE6E6;<%= link_to "登録", [:new, :user_registration],
	    {:accesskey => "5"} %><br/>
	    &#xE6E7;<%= link_to "パスワード忘れ", "#",
	    {:accesskey => "6"} %><br/>
	    &#xE6E8;<%= link_to "登録確認メール再送信", "#",
	    {:accesskey => "7"} %><br/>
	<% end %>
</font>
</div>
<div align="center">
	<font size="2">
		(C) EcSite, inc. <%= Time.now.year %>
	</font>
</div>

app/views/layouts/_footer_smart_phone.html.erb
<div data-role="navbar" >
	<ul>
		<li><%= link_to "トップページ", :controller => "/welcome", :action => "index" %></li>
		<li><%= link_to "商品一覧", :controller => "/items", :action => "index" %></li>
		<li><%= link_to "送料・お支払について", "#" %></li>
		<li><%= link_to "お問い合わせ", "#" %></li>
	<% if user_signed_in? %>
	    <% if current_user.name %>
	        <li class="username">ようこそ<%= current_user.name %>さん</li>
	    <% end %>
	        <li><%= link_to "マイページ", "#" %></li>
	        <li><%= link_to "ログアウト", [:destroy, :user_session] %></li>	
	<% else %>
	    <li><%= link_to "ログイン", "#" %></li>
	    <li><%= link_to "登録", "#" %></li>
	    <li><%= link_to "パスワード忘れ", "#" %></li>
	    <li><%= link_to "登録確認メール再送信", "#" %></li>
	<% end %>
	</ul>
</div><!-- /navbar -->
&copy: EcSite, inc. <%= Time.now.year %>

app/views/layouts/_header.html.erb
<h1>EcSite</h1>
<div id="usermenu">
	<ul>
		<% if current_user %>
		  <% if current_user.name %>
		      <li class="username">ようこそ<%= current_user.name %>さん</li>
		  <% end %>
		  <li><%= link_to "マイページ", "#" %></li>
		  <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
		<% else %>
		  <li><%= link_to "登録", [:new, :user_registration] %></li>
		  <li><%= link_to "パスワード忘れ", [:new, :user_password] %></li>
		  <li><%= link_to "登録確認メール再送信", "#" %></li>
		<% end %>
	</ul>
</div>

<ul class="menu">
	<li><%= link_to "トップページ", :controller => "/welcome", :action => "index" %></li>
	<li><%= link_to "商品一覧", :controller => "/items", :action => "index" %></li>
	<li><%= link_to "送料・お支払について", "#" %></li>
	<li><%= link_to "お問い合わせ", "#" %></li>
</ul>

app/views/layouts/_header_mobile.html.erb
<div align="center">
    <b>EcSite</b>
    <% if current_user %>
        <% if current_user.name %>
                          ようこそ<%= current_user.name %>さん
        <% end %>
    <% end %>
<div>

app/views/layouts/_header_smart_phone.html.erb
<h1>EcSite</h1>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Web App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>EcSite</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="header">
			<%= render :partial => "layouts/header" %>
		</div>
		<div id="contents">
			<% if notice %>
			  <p class="notice"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert"><%= alert %></p>
			<% end %>
			<%= yield %>
		</div>
		<div id="footer">
			<%= render :partial =>"layouts/footer" %>
		</div>
	</body>
</html>

app/views/layouts/application_mobile.html.erb
<html>
	<head>
		<title>ECSite</title>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render :partial => "layouts/header" %>
		<% if notice %>
		    <font color="red"><%= notice %></font>
		<% end %>
		<% if alert %>
		    <font color="blue"><%= alert %></font>
		<% end %>
		<%= yield %>
		<%= render :partial => "layouts/footer" %>
	</body>
</html>

app/views/layouts/application_smart_phone.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>EcSite</title>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!-- <%= stylesheet_link_tag    "application", "data-turbolinks-track" => true %> -->
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.css" />
		<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
		<script src="http://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.js"></script>

		<%= csrf_meta_tags %>
	</head>
	<body>
		<div data-role="page">
			<div data-role="header">
				<%= render :partial => "layouts/header" %>
			</div>
			
			<div data-role="content">
				<% if notice %>
				    <p class="notice"><%= notice %></p>
				<% end %>
				<% if alert %>
				    <p class="alert"><%= alert %></p>
				<% end %>
				<%= yield %>
			</div>
			
			<div data-role="footer">
				<%= render :partial => "layouts/footer" %>
			</div><!-- /footer -->

		</div>

	</body>

</html>

app/views/layouts/assets.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Web App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/purchase/index.html.erb
<h2>購入時のご注意</h2>
<ul class="list">
	<li>当店では銀行振込確認後に商品を送付いたします。</li>
</ul>

以上のご注意に同意される方は、以下のリンクから送付先をご入力ください。

app/views/purchase/index_mobile.html.erb
<div align="center">
	購入時のご注意
</div>
<br />

&#xe6e2; 当店では銀行振込確認後に商品を送付いたします。<br />
<br />

以上のご注意に同意される方は、以下のリンクから送付先をご入力ください。
<br />
<br />

app/views/purchase/index_smart_phone.html.erb
<h2>購入時のご注意</h2>

<ul class="list">
	<li>当店では銀行振込確認後に商品を送付いたします。</li>
</ul>

<p>
	以上のご注意に同意される方は、以下のリンクから送付先をご入力ください。
</p>

app/views/welcome/index.html.erb
<p>ようこそECサイトへ</p>